### PR TITLE
Added a fuzzer for OSS-Fuzzer.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Hi,
I starting fuzzing Lexbor and have created an initial integration with OSS-Fuzz. The fuzzer is in the pull request and the integration with OSS-Fuzz will occur in their own repository (https://github.com/google/oss-fuzz). The build itself occurs within OSS-Fuzz and the code will be continuously fuzzed. If you are interested then please merge the request and provide me with an email to which bug reports will be sent - notice this email will be publicly visible. I am happy to continue creating fuzzers for the project if you would like - I think it would be nice to integrate it as the project is progressing! 

David

### CODE REVIEW

**Comment by lexborisov** [comment]
Hi @DavidKorczynski
 
Thanks for the patch!

1. Little changes for the patch:
```C
#include <lexbor/encoding/encoding.h>


int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    lxb_status_t status;
    const lxb_char_t *start, *end;
    const lxb_encoding_data_t *encoding;

    lxb_codepoint_t cp[32];
    lxb_encoding_decode_t decode = {0};
    lxb_encoding_t encoding_type = (lxb_encoding_t) (data[0] % 0x2b);

    encoding = lxb_encoding_data(encoding_type);

    status  = lxb_encoding_decode_init(&decode, encoding, cp,
                                       sizeof(cp) / sizeof(lxb_codepoint_t));
    if (status != LXB_STATUS_OK) {
        return 0;
    }

    start = (lxb_char_t *) data;
    end = start + size;

    encoding->decode(&decode, &start, end);

    return 0;
}
```

2. How it run? This is for [libfuzzer](https://llvm.org/docs/LibFuzzer.html)?
3. File path: test/fuzzers/lexbor/encoding/decode.c

If oss needs google account: lex.borisov@gmail.com
or if not: borisov@lexbor.com

**Comment by DavidKorczynski** [comment]
> 1. How it run? This is for [libfuzzer](https://llvm.org/docs/LibFuzzer.html)?
More generally it is for multiple fuzzers, as OSS-Fuzz runs several (LibFuzzer, AFL and Hongfuzz). The entry is a topical LibFuzzer entry though, exactly the link you gave. The code will be run on Googles machines and you can find the pull request here to see the infrastructure around it: https://github.com/google/oss-fuzz/pull/3634 (I also added your email.).  
> 2. File path: test/fuzzers/lexbor/encoding/decode.c
 Fixed.

**Comment by lexborisov** [comment]
@DavidKorczynski 

Great! Thanks!

1. About OSS-Fuzz patch: 
1.1. `language: c` not `c++`.
1.2. Not need to use `-DLEXBOR_BUILD_SEPARATELY=ON` in this case, use only `cmake ..`
1.3. `$CC $CFLAGS -I/src/lexbor/source -Wall -pedantic -pipe -std=c99 -fPIC -c  /srx/lexbor/test/fuzzers/lexbor/encoding/decode.c` typo in path `/srx`?

**Comment by DavidKorczynski** [comment]
Thanks! The `c++` thing is there for OSS-Fuzz's purpose: it has problems building when the language is set to `C` (not anything to do with Lexbor). 
Fixed the other issues!

**Comment by DavidKorczynski** [comment]
Hi @lexborisov 
Please merge here so we can get OSS-Fuzz Travis to complete successfully!

**Comment by lexborisov** [comment]
@DavidKorczynski 

Done!
Thanks for the patch!

**Comment by DavidKorczynski** [comment]
Thanks @lexborisov 
The oss-fuzz PR passes Travis so we should be good to go. 
I would be glad to continue creating fuzzers for Lexbor and think it would be nice to have as the project is progressing fast - would you be happy for me to continue contributing in this area?

**Comment by lexborisov** [comment]
@DavidKorczynski 

I will be very grateful if you continue contributing in this area.

Thanks a lot!

**Pull request merged**
