### PR TITLE
Vtorri build system

### PR DESCRIPTION
**Pull request by vtorri**

### CODE REVIEW

**Comment by lexborisov** [comment]
Hi @vtorri 

1. add initial support of meson build system
2. Fix build on Windows (MSYS2+gcc and VS)

These are two different patches. No need to combine them.

I do not want to support the Meson build system. Will you do it yourself?
I will not accept a patch that does not do anything to the end.

If you add new build system, then it should (minimum req.):
1. Single and separately libraries.
2. Build examples.

About patch naming.
1. Everything in the past tense.
```
Bad:
Add initial support of meson build system.

Good:
Added initial support of meson build system.
```

2. Capital letter:
```
Bad:
Added initial support of meson build system.

Good:
Added initial support of meson build system.
```

3. Mandatory dot at the end.
```
Bad:
Added initial support of meson build system

Good:
Added initial support of meson build system.
```

**Comment by vtorri** [comment]
ok, this meson patch still remains in my PR what ever I do. You are right, it should not be there
so, i will close this PR after doing only build system.

ok for the subject (but your point 2 seems to have a problem : both text are the same

and yes, if there is a meson build system, I will support it.

**Comment by vtorri** [comment]
so the title should be : 

Fixed build on Windows (MSYS2+gcc and VS).

right ?

**Comment by lexborisov** [comment]
> so the title should be :
> 
> Fixed build on Windows (MSYS2+gcc and VS).
> 
> right ?

Yes!

**Comment by vtorri** [comment]
closed, in favor of PR #66

**Pull request closed without merging**
